### ISSUE TITLE
Cannot determine whether an audio file is playing

### ISSUE THREAD

**Issue by thomasboevith** [vorple/inform6#12]
I could not get VorpleIsAudioFilePlaying to work. But this fix should enable determining whether an audio file is playing:

```
[ VorpleIsAudioFilePlaying file ;
    VorpleExecuteJavaScriptCommand(BuildCommand("vorple.audio.isElementPlaying('.vorple-audio[src=@@92''+vorple.options.resource_paths.audio+'/", VorpleEscape(file), "@@92']')"));
    return VorpleWhatBooleanWasReturned();
];
```

**Comment by hlabrand** [comment]
Thanks for the fix! Turns out there was an error in VorpleWhatBooleanWasReturned, and a more serious one in compare_string*. So that should fix all sorts of other issues we havent ran into yet ;)
Thanks for your help!

* turns out an array filled by print_to_array starts at WORDSIZE, when an array filled by reading a file starts at 0... Odd behavior
