### ISSUE TITLE
Hack to display notifs on the first turn

### ISSUE THREAD

**Issue by hlabrand** [vorple/inform6#18]
Line 967: we use LookRoutine to run the notifications fallback on the very first turn, because the fallback is put in an "each_turn" and "each_turn" is run at the end of a turn.

Is there a nicer way to do this without using LookRoutine, which might be used by the author's code already? For instance, should we run the fallback when we draw the prompt, which should be the last thing we do in a turn? Or does that create other problems?

**Comment by juhana** [comment]
In I7 the notification fallback is designed to emulate the built-in score notification system ("Your score has gone up by 10") so it might be reasonable to do so in the I6 version too and see how the score notification does it.

When the game file is played on a non-Vorple interpreter the game always does pretty much the same thing before the first turn, so the author should know if the fallback is needed before the first turn or not. If it is, they can print it manually or handle it otherwise, so I don't think it's a big problem if the fallback isn't shown at the start of the game.

**Comment by hlabrand** [comment]
Solved in 3e9dfab (putting it before the prompt, with the interface update, did the trick!)
