### ISSUE TITLE
isVorpleSupported() returns 0 in browser

### ISSUE THREAD

**Issue by Oreolek** [vorple/inform6#28]
The function isVorpleSupported() returns 0 for some reason. Vorple 3.1, Inform 6.33, RInform library, nothing else.

Code: https://code.oreolek.ru/oreolek/vorple-bugtest

**Comment by juhana** [comment]
Hi, sorry about the delay checking the issue, and thanks for the bugtest repo. This is the relevant code from there:

```
[ChangeBackground;
  VorpleExecuteJavaScriptCommand("myNamespace.jumpCount++; return myNamespace.jumpCount");
  print "You have jumped ";
  PrintStringOrArray(VorpleWhatNumberWasReturned());
  print " times!";
  rtrue;
];
#endif;

[ Initialise;
  player.description = "You wear a grim expression.";
  #Ifndef TARGET_ZCODE;
    ! If you remove this line, the game UI hangs
    if (isVorpleSupported() == 1) {
      VorpleInitialise();	! this initialises Vorple
      VorpleNotification("Welcome to Vorple!");
      ChangeBackground();
    }
  #endif;

 "Frogs and snails^
  And puppy-dogs' tails";
];
```

`isVorpleSupported()` always returns 0 before `VorpleInitialise()` is called, so it should be:

```
VorpleInitialise();
if (isVorpleSupported() == 1) {
  VorpleNotification("Welcome to Vorple!");
  ChangeBackground();
}
```

`VorpleInitialise()` should be called first before doing anything else, and it's safe to do so even in normal interpreters. It sets the value of what `isVorpleSupported()` returns. We should bring up this point more prominently in the docs.

The hang mentioned in the comments is caused by this line:

```
PrintStringOrArray(VorpleWhatNumberWasReturned());
```

`VorpleWhatNumberWasReturned()` returns a number but `PrintStringOrArray()` expects a string or an array so the type mismatch causes the problem. You can print the number normally with just `print VorpleWhatNumberWasReturned()`. This is a mistake in the documentation, sorry about that. I'll fix it there.
