### ISSUE TITLE
VorpleStartPlaylist() crashes the interpreter when calling VorpleEscape

### ISSUE THREAD

**Issue by joshwarecom** [vorple/inform6#31]
Best I can tell, the following snippet in the VorpleStartPlaylist causes the terp to hang:

    for (i=0: i<len: i++) {
        print "'"; print (string) VorpleEscape(playlist-->i); print "',";
    }
…and if I change it to the following, the problem goes away:

    for (i=0: i<len: i++) {
        print "vorple.options.resource_paths.audio+'";
        PrintStringOrArray(VorpleEscape((playlist-->(i+1))));
        print "',";
    }

Hypothesis:
print (string) really doesn’t like the return value of VorpleEscape, while VorpalEscape understandably likes playlist–>(i+1) a lot more than playlist–>i

**Comment by hlabrand** [comment]
Hi, thanks for your report! I'm not on my computer right now but:
- yes, the return type of VorpleEscape is an array (strings cannot be changed or manipulated in z-machine, or glulx i believe)
- if you write print "'", (PrintStringOrArray) playlist-->i, "'" it should work
- if not maybe it's because you're printing the -->0, which often is the length of the array and not a string? Not entirely sure about this, it might depend on the type of array, i'm a bit rusty haha
Let me know!
________________________________
De : joshwarecom ***@***.***>
Envoyé : vendredi 28 mai 2021 17:29:21
À : vorple/inform6
Cc : Subscribed
Objet : [vorple/inform6] VorpleStartPlaylist() crashes the interpreter when calling VorpleEscape (#31)


Best I can tell, the following snippet in the VorpleStartPlaylist causes the terp to hang:

for (i=0: i<len: i++) {

    print "'"; print (string) VorpleEscape(playlist-->i); print "',";

}



…and if I change it to the following, the problem goes away:

for (i=0: i<len: i++) {

    print "vorple.options.resource_paths.audio+'";

    PrintStringOrArray(VorpleEscape((playlist-->(i+1))));

    print "',";

}



Hypothesis:
print (string) really doesn’t like the return value of VorpleEscape, while VorpalEscape understandably likes playlist–>(i+1) a lot more than playlist–>i

**Comment by joshwarecom** [comment]
**"'", (PrintStringOrArray) playlist-->i**, "'" still causes it to freeze, I agree it's likely because it's trying to treat the array length as something else.  **i+1** does the trick.

Additionally **print "vorple.options.resource_paths.audio+'";** needs to be prepended, otherwise it doesn't request the audio file from the correct directory and gets a 404 if vorple.options.resource_paths.audio is specified in the play.html.

**Comment by hlabrand** [comment]
..... i completely misunderstood your bug report didnt I? :D
(Sorry! It's just that sometimes people come here asking about why their own code doesnt work!)

I will fix it tomorrow, thank you so much for your report!!
________________________________
De : joshwarecom ***@***.***>
Envoyé : vendredi 28 mai 2021 19:27:46
À : vorple/inform6
Cc : hugo; Comment
Objet : Re: [vorple/inform6] VorpleStartPlaylist() crashes the interpreter when calling VorpleEscape (#31)


"'", (PrintStringOrArray) playlist-->i, "'" still causes it to freeze, I agree it's likely because it's trying to treat the array length as something else. i+1 does the trick.

Additionally print "vorple.options.resource_paths.audio+'"; needs to be prepended, otherwise it doesn't request the audio file from the correct directory and gets a 404 if vorple.options.resource_paths.audio is specified in the play.html.
